# Site settings
title:          adr1's articles
description:    "Hello World"
url:            https://adr1-h.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       20

# Links to social media
social:
  email: temp@gmail.com
  github: https://github.com/adr1-h
  twitter: https://x.com/adr1_h
  twitch: https://www.twitch.tv/adr1_h_
  youtube: https://www.youtube.com/adr1-h
  buymeacoffee: https://buymeacoffee.com/adr1-h

include:
  - _pages

