# Site settings
title:          gh0st's articles
description:    "Hello World"
url:            https://gh0stx86.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       20

# Links to social media
social:
  email: inelaah@gmail.com
  github: https://github.com/gh0stx86
  twitter: https://x.com/gh0stx86
  twitch: https://www.twitch.tv/gh0stx86
  youtube: https://www.youtube.com/@gh0st_pwn
  buymeacoffee: https://buymeacoffee.com/gh0stx

include:
  - _pages

