# Site settings
title:          g04ty's articles
description:    "Hello World"
url:            https://g04ty.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       20

# Links to social media
social:
  email: temp@gmail.com
  github: https://github.com/g04ty
  twitter: https://x.com/g04ty
  twitch: https://www.twitch.tv/g04ty_
  youtube: https://www.youtube.com/g04ty
  buymeacoffee: https://buymeacoffee.com/g04ty

include:
  - _pages

