# Site settings
title:          hg04t's articles
description:    "Hello World"
url:            https://hg04t.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       20

# Links to social media
social:
  email: temp@gmail.com
  github: https://github.com/hg04t
  twitter: https://x.com/hg04t
  twitch: https://www.twitch.tv/hg04t
  youtube: https://www.youtube.com/hg04t
  buymeacoffee: https://buymeacoffee.com/hg04t

include:
  - _pages

