# Site settings
title:          bre4k's articles
description:    "Hello World"
url:            https://bre4kk.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       20

# Links to social media
social:
  email: temp@gmail.com
  github: https://github.com/bre4kk
  twitter: https://x.com/bre4kk_
  twitch: https://www.twitch.tv/bre4kk_
  youtube: https://www.youtube.com/bre4kk
  buymeacoffee: https://buymeacoffee.com/bre4k

include:
  - _pages

